MD007:
  indent: 4

MD013: false

MD040:
  allowed_languages: [
    'html', 'css', 'js', 'ts', 'vue', 'react', 'jsx', 'json', 'jsonc',
    'py', 'java', 'c', 'cpp',
    'bat', 'ps1', 'sh', # 这些表示的是文件
    'shell',            # shell 表示的是命令行，包括 cmd, powershell, bash 中运行的命令
    'text', 'syntax', 'draw' ] # text 表示纯文本、syntax 表示格式，draw 表示字符绘制（要求对齐）
  language_only: true # 为 true 时，将不允许在语言后添加信息，比如 js start-line=2
